# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Informática Básica
#
# @author Helena Gutiérrez Espinosa
# @date 24 nov 2022
# @brief A Makefile for P15695.cc
# 
OBJ = P15695.o
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
        $(CXX) $(CXXFLAGS) P15695.o -o P15695

clean:
        rm -rf *.o *.txt 
        rm P15695